### PR TITLE
Prepare for release of new version

### PR DESCRIPTION
**Pull request by tal-sapan**

### CODE REVIEW

**Comment by bd82** [comment]
In the future you can consider adding links to the change log
example:
https://github.com/SAP/chevrotain/blob/master/docs/changes/CHANGELOG.md

**Comment by tal-sapan** [comment]
There were no related issues for these changes

**Comment by tal-sapan** [comment]
Should it be a minor or patch version?

**Comment by bd82** [comment]
subjective, I would go with minor because rearranging docs is more than a patch

**Comment by tal-sapan** [comment]
I can't release from my computer because the tests fail on Windows. Could you do it?

**Comment by bd82** [comment]
Yes, but the root problem of running on windows should still be resolved
and it would be difficult for me to resolve it without a windows machine...

**Comment by bd82** [comment]
release job is running here:
https://circleci.com/gh/SAP/webide-client-tools/276

**Comment by tal-sapan** [comment]
Thanks.
It should definitely be resolved, but it shouldn't postpone a release. We should fix this ASAP. (And also maybe setup a manually-triggered job to do it instead of running it manually from a user's computer, is this possible?)

**Pull request merged**
